---
apiVersion: v1
kind: Service
metadata:
  name: maven-project-service
  labels:
    name: maven-project-service
    app: maven-project

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: maven-project
    app: maven-project
