---
- hosts: webservers
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_image_name: "anurag2000/project1"
    github_repo_url: "https://github.com/Anurag000-rgb/project1.git"
    dockerhub_username: "dockerhub-username"
    dockerhub_password: "dockerhub-password"
    dockerhub_repo_name: "anurag2000/project1"

  tasks:
  - name: Copy file
    copy:
        src: /var/lib/jenkins/workspace/maven-project/target/ABCtechnologies-1.0.war # Replace this with the path of the file on the control node
        dest: /home
  - name: install docker
    dnf: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    dnf: name=git state=present
  - name: clone a repo
    git: repo="{{ github_repo_url }}" dest="/tmp/project1"

  # - name: Copy file from master to host
  #   copy:
  #     src: /var/lib/jenkins/workspace/CICD-Pipeline/target/ABCtechnologies-1.0.war
  #     dest: deploy.war

  - name: Build Docker image
    become: true
    command: docker build -t {{ dockerhub_repo_name }}:latest .
    args:
      chdir: /tmp/project1
    # community.docker.docker_image:
    #     build:
    #       path: "/tmp/project1"
    #     name: "{{ docker_image_name }}"
    #     state: present

  - name: Login to DockerHub
    become: true
    command: docker login -u {{ dockerhub_username }} -p {{ dockerhub_password }}

    # community.docker.docker_login:
    #     registry_url: "https://hub.docker.com/u/anurag2000"
    #     username: "{{ dockerhub_username }}"
    #     password: "{{ dockerhub_password }}"
   

  - name: Tag and push to docker hub
    community.docker.docker_image:
      name: "{{ docker_image_name }}"
      repository: "{{ dockerhub_repo_name }}"
      push: true
      source: local

    # community.docker.docker_image:
    #     name: "{{ docker_image_name }}"
    #     tag: "{{ dockerhub_repo_name }}"
    #     source: local


    # community.docker.docker_image:
    #     name: "{{ dockerhub_repo_name }}"
    #     push: yes

  - name: Start Docker container
    docker_container:
        name: "{{ docker_image_name }}"
        image: "{{ dockerhub_repo_name }}"
        state: started
        ports:
          - "1234:8080"


  #  - name: Tag Docker image
  #  become: true
  #  command: docker tag {{ docker_image_name }}:{{ dockerhub_repo_name }} {{ dockerhub_username }}/{{ docker_image_name }}:{{ dockerhub_repo_name }}




